### NumPy 
NumPy is a fundamental library for scientific computation in Python . It provides support for arrays and matrices ,along with a collenction of mathematical functions to operate on these data structures. 

In [2]:
import numpy as np

In [4]:
## Create an array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) ## total elements

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
## 2D array
arr2 = np.array([[1,2,3],[90,89,22]])
print(arr2)
print(arr2.shape)

[[ 1  2  3]
 [90 89 22]]
(2, 3)


In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4)) # 3-rows # 4-columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr  = np.array([[1,2,3],[4,5,6]])
print("Array\n",arr)
print("Shape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("Size(Num. of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item Size(in Bytes):",arr.itemsize)

Array
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size(Num. of elements): 6
Data Type: int32
Item Size(in Bytes): 4


In [9]:
### Numpy vectorised operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

## Element wise addition 
print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction:",arr1-arr2)

## Element wise multiplication
print("Multiplication:",arr1*arr2)

## Element wise Division
print("Division:",arr1/arr2)

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [11]:
## Universal function


arr = np.array([1,2,3,4,5])

## square
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [12]:
## Array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])

print(arr[1][0])
print(arr[1][1])
print(arr[1][2])

print(arr[2][0])
print(arr[2][1])
print(arr[2][2])


1
2
3
4
5
6
7
8
9


In [16]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
arr[1:,2:]

array([[6],
       [9]])

In [19]:
## Modify array elements
arr[1:]=100
print(arr)

[[  1   2   3]
 [100 100 100]
 [100 100 100]]


In [20]:
### Statistical concepts -- Normalisation
### to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
mean= np.mean(data)
std_dev = np.std(data)

## Noramalisation
normalised_data = (data-mean)/std_dev
print("Normalised data:",normalised_data)



Normalised data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
mean = np.mean(data)
print("Mean:",mean)

median = np.median(data)
print("Median:",median)

std_dev = np.std(data)
print("Standard Deviation:",std_dev)

variance = np.var(data)
print("Variance:",variance)


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [ ]:
## Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
data[(data>5) & (data<8)]

array([6, 7])