### NumPy 
NumPy is a fundamental library for scientific computation in Python . It provides support for arrays and matrices ,along with a collenction of mathematical functions to operate on these data structures. 

In [1]:
import numpy as np

In [4]:
## Create an array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) ## total elements

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
## 2D array
arr2 = np.array([[1,2,3],[90,89,22]])
print(arr2)
print(arr2.shape)

[[ 1  2  3]
 [90 89 22]]
(2, 3)


In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4)) # 3-rows # 4-columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr  = np.array([[1,2,3],[4,5,6]])
print("Array\n",arr)
print("Shape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("Size(Num. of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item Size(in Bytes):",arr.itemsize)

Array
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size(Num. of elements): 6
Data Type: int32
Item Size(in Bytes): 4


In [ ]:
### Numpy vectorised operations
